#!/bin/sh
#
#
#   startup/shutdown script for lemon.py
#
#   Linux chkconfig:
#
#   chkconfig: 345 89 11
#   Provides: lemon
#   Required-Start: $network 
#   Default-Start: 2 3 4 5
#   Default-Stop: 0 1 6
#   description: Startup/shutdown script for lemon 
#


case $1 in
        start)
                /usr/local/sbin/lemon.py start
        ;;
        stop)
                /usr/local/sbin/lemon.py stop
        ;;
        restart)
                /usr/local/sbin/lemon.py stop
                /usr/local/sbin/lemon.py start
        ;;
        *)

        echo $"Usage: $prog {start|stop|restart}"
        exit 1
esac

exit 0
